# Generated by Django 4.2.1 on 2023-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcribe",
            name="video_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
