# Generated by Django 4.2.1 on 2023-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0004_alter_transcribe_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcribe",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
