# Generated by Django 4.2.1 on 2023-05-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0005_transcribe_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcribe",
            name="url",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
