# Generated by Django 4.2.1 on 2023-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0006_alter_transcribe_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcribe",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
