# Generated by Django 4.2.1 on 2023-05-04 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0007_transcribe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcribe",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
