# Generated by Django 4.2.1 on 2023-05-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0008_transcribe_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcribe",
            name="word_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
