# Generated by Django 4.2.1 on 2023-05-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0009_transcribe_word_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcribe",
            name="price_per_word",
            field=models.DecimalField(decimal_places=2, default=0.04, max_digits=9),
        ),
        migrations.AlterField(
            model_name="transcribe",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
