# Generated by Django 4.2.1 on 2023-05-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0011_alter_transcribe_price_per_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcribe",
            name="price_per_word",
            field=models.DecimalField(decimal_places=5, default=0.00157, max_digits=9),
        ),
    ]
