# Generated by Django 4.2.1 on 2023-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0012_alter_transcribe_price_per_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcribe",
            name="video_len",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
