# Generated by Django 4.2.1 on 2023-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0014_alter_transcribe_video_len"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcribe",
            name="video_len",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
