# Generated by Django 4.2.1 on 2023-05-05 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0015_alter_transcribe_video_len"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transcribe",
            options={"ordering": ["-created_at"]},
        ),
    ]
